### ISSUE TITLE
App is not working with Brave

### ISSUE THREAD

**Issue by john-light** [rsksmart/2wp-app#212]
Brave is a Chromium-based browser and even uses a Chromium user agent, however when visiting https://2wp-app.rsk.co/ in Brave the user is still shown this error message:

> Only Chrome browser is allowed

![Screenshot 2022-04-14 075150](https://user-images.githubusercontent.com/9424721/163386792-2259c615-e543-4b56-92a3-701cec7b0b2c.png)

I am confused about why _Chrome_, specifically, is required to use this app, and not any Chromium-based browser (or for that matter, why the app doesn't work in every browser, as browsers are general-purpose platforms and there shouldn't be a difference in compatibility of web pages using common web standards).

**Comment by josedahlquist** [comment]
Thanks for reaching out @john-light 
Next release will allow Chromium user agent, including Brave.

**Comment by bitcoinuser** [comment]
Any news on this?

**Comment by josedahlquist** [comment]
Hey @john-light and @bitcoinuser glad to tell you that you can try the official release on https://2wp-app.rsk.co/ where Brave is allowed again
